apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-admin-server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-admin-server-deploy
  template:
    metadata:
      labels:
        app: app-admin-server-deploy
    spec:
      containers:
      - name: app-admin-server-deploy
        image: myskillskit/admin-server
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8060

---
apiVersion: v1
kind: Service
metadata:
  name: app-admin-server-deploy
spec:
  type: LoadBalancer
  selector:
    app: app-admin-server-deploy
  ports:
    - port: 8060
      targetPort: 8060