spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: Z9qxg*tN3HD

  mail:
    username: test@gmail.com
    password: '***********'
    host: smtp.gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  boot:
    admin:
      monitor:
        status-interval: 10s
        status-lifetime: 10s
      notify:
        telegram:
          chat-id: '963392265'
          enabled: true
          auth-token: '*****************************'
          ignore-changes: UNKNOWN:UNKNOWN #show all
        mail:
          to: mytest@gmail.com
          enabled: true
#          cc: test33@gmail.com, test44@gmail.com
          ignore-changes: UNKNOWN:UNKNOWN #show all
      ui:
        title: Anatolii Spring Boot Admin
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>Anatolii Spring
          Boot Admin</span>
server:
  port: 8060
logging:
  level:
    root: info